export const FONT_IMPORT_URL = 'https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap';
export const typography = {
  fontFamily: {
    sans:    "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    mono:    "'SF Mono', 'Fira Code', 'JetBrains Mono', 'Cascadia Code', monospace",
  },
  fontWeight: {
    light:     300,
    regular:   400,
    medium:    500,
    semibold:  600,
    bold:      700,
    extrabold: 800,
  },
  fontSize: {
    '2xs':  '0.625rem',    
    'xs':   '0.75rem',     
    'sm':   '0.8125rem',   
    'base': '0.875rem',    
    'md':   '0.9375rem',   
    'lg':   '1.0625rem',   
    'xl':   '1.25rem',     
    '2xl':  '1.5rem',      
    '3xl':  '1.875rem',    
    '4xl':  '2.25rem',     
    '5xl':  '3rem',        
    '6xl':  '3.75rem',     
  },
  lineHeight: {
    none:    1,
    tight:   1.2,
    snug:    1.35,
    normal:  1.5,
    relaxed: 1.625,
    loose:   1.8,
  },
  letterSpacing: {
    tighter: '-0.04em',
    tight:   '-0.025em',
    normal:  '0em',
    wide:    '0.025em',
    wider:   '0.05em',
    widest:  '0.1em',
  },
  styles: {
    displayLg: {
      fontSize: '3.75rem',
      fontWeight: 800,
      lineHeight: 1,
      letterSpacing: '-0.04em',
    },
    displayMd: {
      fontSize: '3rem',
      fontWeight: 800,
      lineHeight: 1,
      letterSpacing: '-0.035em',
    },
    displaySm: {
      fontSize: '2.25rem',
      fontWeight: 700,
      lineHeight: 1.1,
      letterSpacing: '-0.03em',
    },
    h1: {
      fontSize: '1.875rem',
      fontWeight: 700,
      lineHeight: 1.2,
      letterSpacing: '-0.025em',
    },
    h2: {
      fontSize: '1.5rem',
      fontWeight: 600,
      lineHeight: 1.25,
      letterSpacing: '-0.02em',
    },
    h3: {
      fontSize: '1.25rem',
      fontWeight: 600,
      lineHeight: 1.3,
      letterSpacing: '-0.015em',
    },
    h4: {
      fontSize: '1.0625rem',
      fontWeight: 600,
      lineHeight: 1.35,
      letterSpacing: '-0.01em',
    },
    bodyLg: {
      fontSize: '0.9375rem',
      fontWeight: 400,
      lineHeight: 1.625,
      letterSpacing: '0em',
    },
    body: {
      fontSize: '0.875rem',
      fontWeight: 400,
      lineHeight: 1.5,
      letterSpacing: '0em',
    },
    bodySm: {
      fontSize: '0.8125rem',
      fontWeight: 400,
      lineHeight: 1.5,
      letterSpacing: '0em',
    },
    caption: {
      fontSize: '0.75rem',
      fontWeight: 500,
      lineHeight: 1.35,
      letterSpacing: '0.025em',
    },
    overline: {
      fontSize: '0.6875rem',
      fontWeight: 600,
      lineHeight: 1.2,
      letterSpacing: '0.1em',
      textTransform: 'uppercase',
    },
    label: {
      fontSize: '0.8125rem',
      fontWeight: 500,
      lineHeight: 1.35,
      letterSpacing: '0em',
    },
    code: {
      fontFamily: "'SF Mono', 'Fira Code', monospace",
      fontSize: '0.8125rem',
      fontWeight: 400,
      lineHeight: 1.5,
    },
  },
};
